### ISSUE TITLE
Describe the process to contribute in JdeRobot project

### ISSUE THREAD

**Issue by rocapal** [RoboticsURJC/JdeRobot#13]
We need to describe the process and policy to third-people in order to contribute in JdeRobot project.

It would be nice have a description and screenshots of the next steps:

* Create a fork
* Modify source code
* Pull request

Here there is a guide of github that we can use: https://guides.github.com/activities/contributing-to-open-source/

**Comment by hustcalm** [comment]
@rocapal 
I'd like to try and hopefully will get this done for one or two days.
So you can assign the issue to me:-)

**Comment by hustcalm** [comment]
@rocapal 
I was just trying to edit the [wiki page](https://github.com/RoboticsURJC/JdeRobot/wiki/) to place the contribution process there. However, I find it better to put a draft here maybe. The wiki pages can be filled later on. Here it goes:-)

<hr />

It's very cool to use Git and Github as the collaborate tools for JdeRobot development. 

The basic workflow would be like:

* Fork the JdeRobot repository
* Clone your own JdeRobot repository using Git
* Create a new branch for new features and bug fixes
* Work on your branch and get it run and tested
* Commit your changes and open a pull request
* Make changes regarding the discussions of your pull request

For now, I'm gonna demo this workflow using my Github account and try to add a dummy feature, since the contribution process is not so well documented, I will start here to add a section named `How To Contribute` to the `README.md` file of the project. Here we go!!!

## Fork the JdeRobot repository
First of all, to make your changes accepted as a contributor, we have to `Fork` the repository. For more roles of a Github project, see [here](https://guides.github.com/activities/contributing-to-open-source/#project).

To fork a repository on Github, just click on the right corner of the project page as illustrated below:
![github_fork_repository](https://cloud.githubusercontent.com/assets/1515226/6773085/c4604132-d146-11e4-9cfe-84f5e62a5d6d.png)

Then follow the panel to choose where your fork should go, typically you will select your personal Github account if you got many choices, for me I choose(@hustcalm) as:
![github_fork_repository_where](https://cloud.githubusercontent.com/assets/1515226/6773141/861f5632-d147-11e4-9df6-80e02fca5fbb.png)

After that, you should be redirected to the new repository under your account, for me, it looks like:
![github_forked_repository_hustcalm](https://cloud.githubusercontent.com/assets/1515226/6773186/32e143c6-d148-11e4-976e-a5da73314670.png)

## Clone your own JdeRobot repository using Git
Once you have forked the repository, it's time to start some hacks on your repository! However, first of all, you have to clone the source code using `Git`:
![github_repository_clone_url](https://cloud.githubusercontent.com/assets/1515226/6773247/fc8c9cb6-d148-11e4-9037-5c8181fe8e25.png)

Basically, you have 3 options:

* HTTPS
* SSH
* Subversion

No big differences, just different protocols. If you have set up your [Github SSH](https://help.github.com/articles/generating-ssh-keys/), I suggest using `SSH`. For using `HTTPS`, you will be prompted to input user name and password when accessing your `Github` repository from terminal. 

Now, open your terminal and `cd` to a proper directory, then `clone`:
![github_jderobot_git_clone](https://cloud.githubusercontent.com/assets/1515226/6773375/8a4b2304-d14b-11e4-932a-dfccc88d6272.png)

## Create a new branch for new features and bug fixes
For contribution, developers will always add new features or fix bugs. For easy development management, we will use `branches`. For default branches after a fresh clone, you can see them by `git branch -a`:
![github_jderobot_branches](https://cloud.githubusercontent.com/assets/1515226/6773394/aa539a96-d14b-11e4-98a6-e4b9820b0825.png)

To create a new branch, use `git branch branch_name`, this will create a new branch based on your current working branch. Like `git branch JdeRobot_how_to_contribute`:
![github_jderobot_new_branch](https://cloud.githubusercontent.com/assets/1515226/6773416/e1b4d6d0-d14b-11e4-8deb-b7b74f6acc7f.png)

Switch to the new branch using `git checkout branch_name`, this will make `branch_name` the current working branch. Like `git checkout JdeRobot_how_to_contribute`:
![github_jderobot_checkout_new_branch](https://cloud.githubusercontent.com/assets/1515226/6773424/0801f868-d14c-11e4-949f-27e9b7b6c0d7.png)

OK, let's have a check to just make sure, you can always run `git status` or `git remote` to see what is going on with your local repository:
![github_jderobot_git_status_remote](https://cloud.githubusercontent.com/assets/1515226/6773436/4265ffcc-d14c-11e4-944d-be329821bb8b.png)

For more useful commands about `Git`, you can always run `git help`.

## Work on your branch and get it run and tested
Well, really time to hack! Now you can concentrate on your new feature or bug fix and show your talent:-)

As for the demo, I will edit the `README.md` file, like:
![github_jderobot_edit_file](https://cloud.githubusercontent.com/assets/1515226/6773512/2cc6c48e-d14d-11e4-9135-0b81213a3ba5.png)

The edited file would be like:
![github_jderobot_working_on_branch](https://cloud.githubusercontent.com/assets/1515226/6773525/4230626c-d14d-11e4-97a1-1967e48b5317.png)

After your hack, make sure your changes are doing well, especially not destroying the compiled source code. Tests are great ways to make things right, so please test your changes and make sure everything is just fine!

## Commit your changes and open a pull request
Once you are done with your feature or bug fix, time to share with the community:-)

Basically, you should:

### Commit your changes
![github_jderobot_commit](https://cloud.githubusercontent.com/assets/1515226/6773550/b31fb96e-d14d-11e4-82ab-861c81eb76d6.png)

### Push to your repository
![github_jderobot_push](https://cloud.githubusercontent.com/assets/1515226/6773559/e7a72a00-d14d-11e4-9682-34316358e998.png)

### Create a pull request
![github_jderobot_compare_pull_request](https://cloud.githubusercontent.com/assets/1515226/6773620/aa9ca4e0-d14e-11e4-8895-00a8c904101f.png)

To create a good pull request, be sure to make things clear:

![github_jderobot_create_pull_request](https://cloud.githubusercontent.com/assets/1515226/6773729/76ddf53a-d150-11e4-9424-b99dfc983f9e.png)

## Make changes regarding the discussions of your pull request
![github_jderobot_pull_request_discusstions](https://cloud.githubusercontent.com/assets/1515226/6773736/804fd1f6-d150-11e4-8639-5f7bbe58a292.png)

Cheers, any comments are welcome, let's make it better together:-)
Lihang

**Comment by hustcalm** [comment]
Created a new wiki page [here](https://github.com/RoboticsURJC/JdeRobot/wiki/How-To-Contribute), hope it helps:-)

**Comment by rocapal** [comment]
@hustcalm awesome!! It's perfect. I'll include it in the wiki of JdeRobot, but just I link the wiki page of github that you have created.

Thanks a lot!!

**Comment by hustcalm** [comment]
@rocapal 
I'm glad it helps and feels really good contributing to JdeRobot:-)

I talked with JoseMaria earlier by Email and maybe I can have write access on the official wiki pages. So I'm thinking about maintaining the `How To Contribution` both on `Github` and `jderobot.org`.

Any feedback is welcome, I'm always ready to polish it:-)

Here is a good [How To Contribution sample](https://wiki.openstack.org/wiki/How_To_Contribute) coming from `OpenStack` project, I think we can do more!!!

Cheers,
Lihang

**Comment by rocapal** [comment]
Closed! If we need some documentation about contribute in the project, we should use this issue again.
