### ISSUE TITLE
The car model of car_apritalgs.world show white wheels in virtualized environment

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#222]
Hi all,

yesterdary I installed a virtual machine (x64) with the new debian packages, I tested the car_apriltags.world with introrob_py and the images received by the plugin show white the wheels car.

![car_with_white_wheels](https://cloud.githubusercontent.com/assets/12018634/11019926/0380e9a2-860f-11e5-8809-8bf80801e784.png)

This only occur in virtualized environments. Does anyone know that happens?

regards

**Comment by fqez** [comment]
Hi @almartinflorido 

the problem is in these lines of the <i>model.sdf</i>:

```
<collision name="collision">
    <geometry>
        <cylinder>
            <radius>0.05</radius>
            <length>0.1</length>
        </cylinder>
    </geometry>
</collision>
<visual name="visual">
    <geometry>
        <cylinder>
            <radius>0.05</radius>
            <length>0.1</length>
         </cylinder>
     </geometry>
</visual>
```

int these links:

```
<link name="{rear,front}_{left,right}_steering_wheel_block">
<link name="{rear,front}_{left,right}_wheel">
```
As long as they only specify visual properties, they are not required. If you comment out this block of code for each wheel in (<i>~/models/carApriltag/model.sdf</i>), you can remove this visual effect. 

I am not sure, but maybe gazebo primitive shapes have visual preferences over textures.

Try it and let me know if you success!

Regards!

**Comment by almartinflorido** [comment]
Yes, with this changes the car don't show the white wheels.

Thank you so much @fqez !!
