### ISSUE TITLE
The ultrasonic altimeter of ardrone plugin doesn't works

### ISSUE THREAD

**Issue by almartinflorido** [RoboticsURJC/JdeRobot#223]
Hi all,

the altimeter of ardrone plugin always return 0, the next image show a drone over a car (aprox two meters in height) for this case the altimeter return 0 and the z axis of absolute pose 3D 4.65m.
![altitude_values](https://cloud.githubusercontent.com/assets/12018634/11020003/7407612c-8611-11e5-946e-2d9a4538db5e.png)

regards

**Comment by fqez** [comment]
Hi @almartinflorido 

the problem is in these lines of the <i>model.sdf</i>:

```
<collision name="collision">
    <geometry>
        <cylinder>
            <radius>0.05</radius>
            <length>0.1</length>
        </cylinder>
    </geometry>
</collision>
<visual name="visual">
    <geometry>
        <cylinder>
            <radius>0.05</radius>
            <length>0.1</length>
         </cylinder>
     </geometry>
</visual>
```
As long as they only specify visual properties, they are not required. If you comment out this block of code for each wheel in (<i>~/models/carApriltag/model.sdf</i>), you can remove this visual effect. 

I am not sure, but maybe gazebo primitive shapes have visual preferences over textures.

Try it and let me know if you success!

Regards!

**Comment by fqez** [comment]
Maybe related with this issue #196?

**Comment by almartinflorido** [comment]
No, the functionality has never been implemented I think.

**Comment by varhub** [comment]
I'm reviewing quadrotor plugin at now, and if altimeter info is part of navdata struct, it is not implemented.

I suppose that it would require something like raytracing.

**Comment by varhub** [comment]
Added to #229 changeset
